module.exports = {

    ignore: [
        "**/components/PActionList/components/*",
        "**/components/PActionMenu/*",
        "**/components/PButton/utils/*",
        "**/components/PCard/",
        "**/components/PCard/PCardFooter.vue",
        "**/components/PCard/PCardHeader.vue",
        "**/components/PDropZone/PDropZone.vue",
        "**/components/PFilter/components/*",
        "**/components/PFormLayout/PFormLayoutGroupItemWrapper.vue",
        "**/components/PFormLayout/PFormLayoutItem.vue",
        "**/components/PChoice/PChoice.vue",
        "**/components/PConnected/*",
        "**/components/PDropZone/*",
        "**/components/PWrapper/PWrapper.vue",
        "**/components/POptionalTag/POptionalTag.vue",
        "**/components/PPageActions/PPageActions.vue",
        "**/components/PPopover/components/PPopoverOverlay.vue",
        "**/components/PPopover/components/PPositionedOverlay.vue",
        "**/components/PResourceList/components/PBulkActionButtonWrapper.vue",
        "**/components/PTextField/components/PFieldResizer.vue",
        "**/components/PDataTable/PDataTableCell.vue",
        "**/components/PDataTable/PDataTableCell.vue",
        "**/components/PFilter/PFilter.vue",
        "**/components/PPage/components/PPageHeader.vue",
        "**/components/PPage/components/components/PPageHeaderTitle.vue",
        "**/components/PPagination/PPagination.vue",
        "**/components/PModal/components/*",
    ],
    require: ['./src/css/polaris.min.css']
}